### ISSUE TITLE
Search returns back 404 - undefined in the GET request

### ISSUE THREAD

**Issue by michaelblythe** [agustinaliagac/crawl-io#35]
I've followed the details as per the readme and deployed via docker. I can see the front-end but when i search i'm not getting any results but a 404 and i've noticed it says 'undefined' in the URL. The exact URL is below. 

http://localhost:3000/undefined/api/search?searchTerm=iphone

Any ideas?
Regards,
Michael

**Comment by agustinaliagac** [comment]
@michaelblythe This was due to a missing .env file in the react app.
Thanks for reporting it!

It should be working now on 'master' branch.
